apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: funnel-worker-sa-{{`{{.Namespace}}`}}-{{`{{.TaskId}}`}}-binding
  namespace: {{`{{.Namespace}}`}}
  labels:
    app: funnel
    taskId: {{`{{.TaskId}}`}}
subjects:
- kind: ServiceAccount
  name: {{`{{.ServiceAccountName}}`}}
  namespace: {{`{{.Namespace}}`}}
roleRef:
  kind: Role
  name: funnel-worker-sa-{{`{{.Namespace}}`}}-{{`{{.TaskId}}`}}-role
  apiGroup: rbac.authorization.k8s.io
